# Generated by Django 5.0.7 on 2024-09-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employee_photos/avatar.jpg', null=True, upload_to='employee_photos/'),
        ),
    ]
