# Generated by Django 5.1.1 on 2024-10-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
