# Generated by Django 5.1.1 on 2024-10-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_offerletter_file_offerletter_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='file',
        ),
        migrations.RemoveField(
            model_name='offerletter',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='file',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='year',
        ),
    ]
