# Generated by Django 5.1.1 on 2024-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_offerletter_file_payroll_file_payroll_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.DateField(blank=True, max_length=7, null=True),
        ),
    ]
