# Generated by Django 5.1.1 on 2024-10-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_payroll_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
    ]
