# Generated by Django 5.1.1 on 2024-11-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_task_completed_task_priority_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=7, null=True),
        ),
    ]
