# Generated by Django 5.1.1 on 2024-12-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_attendance_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(),
        ),
    ]
